apiVersion: v1
kind: Service
metadata:
  name: django-nodeport-service
spec:
  selector:
    app: django
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000       # Internal Cluster Port
      targetPort: 8000  # Django Container Port
      nodePort: 30008   # External Node Port (Range: 30000-32767)
